# Generated by Django 2.2.3 on 2019-11-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='profile',
            field=models.TextField(default='互联网大佬'),
            preserve_default=False,
        ),
    ]
